spring.application.name=wallet-service
server.port=${wallet-service.uriport}

spring.cloud.config.profile=dev
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.datasource.url=${wallet-service.datasource-url}
spring.jpa.defer-datasource-initialization=true
spring.datasource.username=${wallet-service.username}
spring.datasource.password=${wallet-service.password}

spring.jpa.hibernate.ddl-auto=${wallet-service.hibernate-ddl-auto}
spring.jpa.show-sql=${wallet-service.showsql}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone: ${wallet-service.urlregistry}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
